language: node_js
node_js:
- node
- lts/*
- '10'
- '8'
script:
- cp examples/src/js/config/config.example.js examples/src/js/config/config.js
- echo "Generating bundle.js…"
- npm run build
- npm run demo
skip_cleanup: true
jobs:
  include:
    - stage: npm release
      node_js: "lts/*"
      script:
        # Copy config for demo
        - cp examples/src/js/config/config.example.js examples/src/js/config/config.js
        - echo "Generating bundle.js…"
        # Only generate bundle, not demo
        - npm run build
        # Only generate demo
        - npm run demo
        - echo "Deploying to npm…"
      deploy:
        on:
          tags: true
        # Do not reset files to send bundle.js
        # to NPMJS
        skip_cleanup: true
        email: ambroise@rezo-zero.com
        provider: npm
        api_key:
          secure: ghCDQ6wIjCRhYb3pfCMydSETFyJFkZ6B74NnyRFMP/7RtWCFv7K+g9xbvzta4ru/Y1lnM+GVYIpd9DkiwkrOi10foFGqSOnYfqDzwXN/DgdM1sgM2hMwWnh3cXljmJzU3MHJuu/QzxJDeadt3hMBo6GrYh5HXwAwAZ5egrnFcJC2x0szuORtGCFHJxV9dxQGyIw6LTwi9tU7sUY+0BNy/IjiMUDlOvSLIguL7VdZnq2/3o9YU+7EWgpCMSm9nKqdA4ChQ0lCKyom5JBTqZjE8O2krvVMbkEcIi9XBYLy8dbtZXZ1DXoA7HAuUgReVf3b6qra8rMCwbrsO7pzwseLvXcAFq4ZM0ZA1Ty04kZlyOmVJMhxDHjHX1mWuPrMCLau18M/E8qpyeUWArSTb2/hW51OKwqTZ2iSaiZVUmkyYpK8o5gI6OSWzMi/9EPAvZe4hl2e3fnYr7Hn4FCYB58lXGfh299KCZSSNuinAmGcRl5euJk/ZLKmpbGaLFJMulhNQcNnxMFsK/2q5m9Uqgv6UM+vF3IuKrWKyanR0PnPedHMhqo/6jWqIAcZ+kwXvC965y0xHFQpElZ45u36NSoqmQTMTr0wM+R6RTgT5808LviegHzSbMgXdDj9rweQphkWK2XnNTsLlFooQSdiXwBmXWgM+VRhPmVLD7eCS9vnI6w=

